### ISSUE TITLE
Bugs with the TOC Add On

### ISSUE THREAD

**Issue by tisonkelley** [goldnead/statamic-toc#7] opened 2021-11-04 20:58 UTC
Hi Goldnead,
Thank you for a cool add on we like it but we found a few bugs when using it, we were able to work around them all, but it keeps causing the page to crash so if you could fix, it would be great.  

Here they are:

Bug Nr. 1) If you have a blank line that is an h3 or h2 (eg you just hit enter and that blank line happens to be styled as an h2), it will break the entire front end of the page (can’t even see the page anymore).

Bug Nr. 2).  If you don’t include an h2 first on the page, and you just include an h3 it bombs out the whole page, cannot view the page anymore.

Bug Nr. 3) If you use an ampersand (&) in your heading, the link to that heading shows but doesn’t work..

Thank you again for all your hard work,
T

**Comment by goldnead** [comment] 2021-11-05 10:52
Hi @tisonkelley,

Thanks for you bug report! I will look into them next week. Do you use the addon on a bard field in html or in structured data (yaml) mode?

**Comment by tisonkelley** [comment] 2021-11-05 12:26
I'm copying Devon here, he will know the answer to this better than I,
Devon for context - This is the TOC developer, I mentioned the bugs we
found to him and he asked this question below,
T

Tison G. Kelley
Breakthrough Strategic Services
(315) 233-9283 ext 704
What We Do: breakthroughdesign.com/work

**Comment by goldnead** [comment] 2021-11-05 15:54
Hey @tisonkelley ,

I just managed to reproduce and fix Bug no. 1 and 3. However I cannot reproduce your second bug. If I add an H3 as the first element in a bard field, with or without any other headings, it appears correctly on my setup.

Could you provide a bit more context to that specific bug? Maybe you could post an example content of your specific bard field in which the error occurs?

**Comment by tisonkelley** [comment] 2021-11-05 19:42
It’s in structured yaml mode for bard, not html.On Fri, Nov 5, 2021 at 8:26 AM, Tison Kelley ***@***.***> wrote:I'm copying Devon here, he will know the answer to this better than I,Devon for context - This is the TOC developer, I mentioned the bugs we found to him and he asked this question below,TTison G. KelleyBreakthrough Strategic Services (315) 233-9283 ext 704What We Do: breakthroughdesign.com/workOn Fri, Nov 5, 2021 at 6:52 AM goldnead ***@***.***> wrote:
Hi @tisonkelley,
Thanks for you bug report! I will look into them next week. Do you use the addon on a bard field in html or in structured data (yaml) mode?

**Comment by goldnead** [comment] 2021-11-06 10:42
Closing this issue as I split all the bugs in separate issues so they're easier to track: #8, #9  and #10.

**Closed by goldnead** 2021-11-06 10:42 UTC
Labels: bug

**Comment by goldnead** [comment] 2021-11-08 08:14
@tisonkelley, could you take a look at issue #10? As mentioned above, I can't reproduce the bug you described so it would be great if you could provide more information or an example so I can try to fix it.

Thanks.
